name: informationplatformdialog
description: displays dialog window with title, content and buttons, respecting the platform in execution.
version: 0.0.1
author: Everton Coimbra de Araújo - evertoncoimbra@gmail.com
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
